shapeSet.push('u/d/l/r/') // #0 可乐类，=╬=
shapeSet.push('lu/ru/ld/rd/') // #1 绿毛类，X
shapeSet.push('lu/l/r/ld/') // #2 丝巾类，C
shapeSet.push('lu/l/r/ld/') // #3 MK23类，╠==
shapeSet.push('u/l/d/') // #4 纳甘类，=╣
shapeSet.push('u/r/d/') // #5 P08类，╠=
shapeSet.push('lu/u/ru/l/r/ld/d/rd/') // #6 竞争者类，▇
shapeSet.push('lu/r/ld/') // #7 C96类，>==
shapeSet.push('u/ru/l/r/ld/d/') // #8 蟒蛇
