lib_lang = {
  sele_selenum: '选择编号',
  sele_selebest: '下面是最优的数个方案',
  sele_noresult: '无合适方案',

  check_M2: '允许空出1~3格(不使用五格2类)',

  btn_clear: '再按一次，确认清空芯片仓库',
  btn_maxall: '再按一次，确认全部满强化',
  btn_blueall: '再按一次，确认只保留【蓝色】芯片',
  btn_orangeall: '再按一次，确认只保留【橙色】芯片',
  btn_savedone: '存储码已复制到剪贴板',
  btn_loaderror: '不正确的存储码',
  btn_showblock: '显示有效格数',
  btn_showvalue: '显示有效属性',

  over_dmg: '杀伤溢出',
  over_dbk: '破防溢出',
  over_acu: '精度溢出',
  over_fil: '装填溢出',

  blo_5: '五格',
  blo_6: '六格',
  shape: '形状',
  num: '编号',
  topo: '图解',
  toponum: '图解编号',
  notopo: '现有芯片不足以拼出图解',
  totaltime: '总时间',
  refer: '按',
  valid_value: '有效总属性',
  valid_block: '有效格数',
  dmg: '杀伤',
  dbk: '破防',
  acu: '精度',
  fil: '装填',
  sorting: '排序',
  have: '有',
  type_of_combi: '种有效组合',
  showall: ' 【全部方案】给出所有可行图解，及每种图解的所有可能和组合(速度很快)',
  showsort: ' 【最优方案】输出最优的数个的方案(约数分钟不等)',

  cs_551: '重装通用芯片',
  cs_552: '以下<b><span style="color:#FF0066">仅用于M2</span></b>'
}
