var lib_language = {
  main_draw_1: '号位:',
  main_draw_2: '  输出=',
  main_formatDPS_1: '时间=',
  main_formatDPS_2: 's, 输出=',
  main_makeGraph_1: '时间',
  main_makeGraph_2: '伤害',
  UI_affect: '影响',
  UI_num: '号位',
  UI_putsee: '放置人形后才能显示受到的增益',
  UI_pickblock: '请点选一个<b><span style="color: red">九宫格</span></b>',
  UI_not_2_python: ' *不能添加两个蟒蛇',
  UI_not_2_carcano: ' *不能添加两个CarcanoM1891',
  NAME_39: '莫辛纳甘',
  skillNAME_39: '沉稳射击',
  skillNAME_39_2: '苍白收割者',
  DESCRIBE_39_1: '每',
  DESCRIBE_39_2: '次普攻击杀敌人',
  DESCRIBE_39_3: '禁用',
  DESCRIBE_39_4: '技能击杀敌人',
  skillNAME_55: '伸冤者印记',
  DESCRIBE_55: '使用炮击',
  INPUT_PI: '输入正整数',
  hp: '生命',
  cs: '弹量',
  dmg: '伤害',
  rof: '射速',
  acu: '命中',
  eva: '回避',
  crit: '暴击',
  critdmg: '暴伤',
  arm: '护甲',
  ap: '穿甲',
  cld: '冷却'
}
