var lib_language = {
  main_draw_1: 'position:',
  main_draw_2: '  dmg=',
  main_formatDPS_1: 'time=',
  main_formatDPS_2: 's, dmg=',
  main_makeGraph_1: 'time',
  main_makeGraph_2: 'dmg',
  UI_affect: 'Affect ',
  UI_num: ' position',
  UI_putsee: 'Place a T-doll to show effect',
  UI_pickblock: '<b>Click a <span style="color: red">block</span> first</b>',
  UI_not_2_python: ' *Unable to place two Python',
  UI_not_2_carcano: ' *Unable to place two CarcanoM1891',

  NAME_39: 'Mosin-Nagant',
  NAME_238: 'Type 88',
  NAME_243: 'Howa Type 64',
  NAME_2006: 'Theresa',

  NAME_4: 'Python',
  NAME_96: 'Grizzly MkV',
  NAME_114: 'Welrod MkⅡ',
  NAME_183: 'Contender',
  NAME_233: 'Px4 Storm',
  NAME_1: 'Colt Revolver',
  NAME_2001: 'Noel',
  NAME_2003: 'Kiana',
  NAME_2009: 'Clear',
  NAME_2010: 'Fail',
  NAME_7: 'Stechkin',
  NAME_202: 'Thunder',
  NAME_248: 'Jericho',
  NAME_5: 'Nagant Revolver',
  NAME_6: 'Tkokarev',
  NAME_8: 'Makarov',
  NAME_13: 'Type 92',
  NAME_14: 'Astra Revolver',
  NAME_15: 'Glock 17',
  NAME_113: 'Serdyukov',
  NAME_132: 'Type 59',
  NAME_129: 'Type 95',
  NAME_130: 'Type 97',
  NAME_2007: 'Murata Himeko',
  NAME_66: 'Type 56-1',
  NAME_171: 'Ribeyrolles',
  NAME_239: 'Type 03',
  NAME_71: 'Galil',
  NAME_133: 'Type 63',
  NAME_16: 'Thompson',
  NAME_115: 'Suomi',
  NAME_228: 'Type 100',
  NAME_150: 'Shipka',
  NAME_203: 'Honey Badger',
  NAME_225: 'Cx4 Storm',
  NAME_29: 'Sten MkⅡ',
  NAME_94: 'Type 64',
  NAME_27: 'Skorpion',
  NAME_32: 'UZI',
  NAME_31: 'Beretta Model 38',
  NAME_50: 'Lee-Enfield',
  NAME_197: 'Carcano M1891',
  NAME_198: 'Carcano M91/38',
  NAME_204: 'Ballista',
  NAME_2004: 'Raiden Mei',
  NAME_2005: 'Bronya',
  NAME_36: 'Springfield',
  NAME_34: 'M1 Garand',
  NAME_49: 'Type 56',
  NAME_95: 'Hanyang Type 88',
  NAME_174: 'Type 81 Carbine',
  NAME_201: 'Gepard M1',
  NAME_255: 'Steyr Scout',
  NAME_41: 'Simonov',
  NAME_112: 'Negev',
  NAME_253: 'Lewis Gun',
  NAME_185: 'Ameli',
  NAME_199: 'Type 80',
  NAME_89: 'Bren',
  NAME_249: 'Type 62',
  NAME_2002: 'Elphelt',
  NAME_2008: 'Seele',
  NAME_161: 'Type 97 Shotgun',
  NAME_256: 'Falcon',
  NAME_127: 'Type 79',

  equipNAME_0: 'No equipment',
  equipNAME_12: 'Telescope Sight',
  equipNAME_14: 'Holographic Sight',
  equipNAME_13: 'Red Dot Sight',
  equipNAME_11: 'Silencer',
  equipNAME_41: 'Night Combat Equipment',
  equipNAME_31: ' Exoskeleton',
  equipNAME_33: ' Armor Plate',
  equipNAME_21: 'ILM Hollow Point Ammo',
  equipNAME_23: 'Mk211 High-Explosive AP Ammo',
  equipNAME_22: 'APCR High-Velocity Ammo',
  equipNAME_24: '#000 Buckshot',
  equipNAME_25: 'SABOT Slug',
  equipNAME_34: 'Thermoptic Camouflage Cape',
  equipNAME_35: 'IOP Maximum Ammo Box',
  equipNAME_11001: 'Colt Revolver Long Barrel',
  equipNAME_11005: 'Nagant Revolver Silencer',
  equipNAME_11091: 'MP446C Competition Barrel',
  equipNAME_42009: 'Glory Light',
  equipNAME_42010: 'Black Cat',
  equipNAME_169: 'FÉLIN System Sight',
  equipNAME_4118: 'PKN03M Night Scope',
  equipNAME_11063: 'G3 Improved Barrel Group',
  equipNAME_11064: 'G36 Hybrid Optics',
  equipNAME_354: 'Custom Exoskeletal Armour',
  equipNAME_11056: 'Dinergate-Type RO',
  equipNAME_11057: 'Light Weight Rail System',
  equipNAME_326: 'GSG UX Exoskeleton',
  equipNAME_3103: 'UMP UX Exoskeleton',
  equipNAME_31093: 'Ability Upgrade Cartridge',
  equipNAME_11037: 'M2 Bipod',
  equipNAME_11051: 'Fire Selector',
  equipNAME_1125: 'MG4 Exclusive MGO',
  equipNAME_11089: 'Bren L4 Barrel Group',
  equipNAME_21002: 'XM261 ACP',
  equipNAME_21057: '.300BLK High-Velocity Ammo',
  equipNAME_236: 'National Match-Grade AP Ammo',
  equipNAME_362: 'High-Perf. Tactical Hair Decoration',
  equipNAME_31055: 'Inherited Weapon Arsenal',
  equipNAME_11029: 'Sten Exclusive Silencer',
  equipNAME_11103: 'Additional Process Module',
  equipNAME_11094: 'Type 64 Exclusive Suppressor',
  equipNAME_342: 'Blue Thickened Cape',
  equipNAME_31039: 'Hayha Memory Chip',
  equipNAME_31044: 'Digital Camouflage Cape',
  equipNAME_388: 'Infinite Ammo Box',
  equipNAME_3185: 'Dedicated Tactical Memory',
  equipNAME_31075: 'Titan Fire Control Chip',

  skillNAME_39: 'Designated Shot',
  skillNAME_39_2: 'Pure White Reaper',
  skillNAME_55: "Avenger's Mark",
  skillNAME_102: 'Overload',
  skillNAME_180: 'Piercing Shot',
  skillNAME_194: 'Overheat',
  skillNAME_213: 'Whimsical Chain',
  skillNAME_231: 'Prophecy of a False God',
  skillNAME_238: 'Slothful Rage',
  skillNAME_243: 'Future Warning',
  skillNAME_252: 'Concussive Strike',
  skillNAME_2006: 'Sanctions of Light',
  DESCRIBE_39_1: 'Each',
  DESCRIBE_39_2: 'attacks kill',
  DESCRIBE_39_3: 'Disabled',
  DESCRIBE_39_4: 'Skill killing',
  DESCRIBE_55: 'Shelling',
  DESCRIBE_102_1: 'Default',
  DESCRIBE_102_2: 'Overload',
  DESCRIBE_180: 'Pierce all enemy',
  DESCRIBE_194_0: 'Active status',
  DESCRIBE_194_1: 'Auto',
  DESCRIBE_194_2: 'Always Fever(3 shot)',
  DESCRIBE_194_3: 'Always Note(1 shot)',
  DESCRIBE_213_0: 'Load status',
  DESCRIBE_213_1: 'Subsonic rounds(eva+65%)',
  DESCRIBE_213_2: 'Spoon point tip(dmg+85%)',
  DESCRIBE_213_3: 'Standard rounds(acu+200%)',
  DESCRIBE_231: 'Victory session',
  DESCRIBE_236: 'Ratio',
  DESCRIBE_238: 'LMG mode',
  DESCRIBE_243_0: 'After 3s',
  DESCRIBE_243_1: 'Dmg+55%',
  DESCRIBE_243_2: 'Sheild 25',
  DESCRIBE_251: 'Lock of Flowers',
  DESCRIBE_252: 'Sputter all enemies',
  DESCRIBE_2006: 'Enemy enter area',

  fairy_0: 'No fairy',
  talent_0: 'No talent',

  enemy_normal: 'Normal',
  enemy_elite: 'Elite',

  INPUT_PI: 'Input integer',

  hp: 'hp',
  cs: 'clipsize',
  dmg: 'dmg',
  rof: 'rof',
  acu: 'acu',
  eva: 'eva',
  crit: 'crit',
  critdmg: 'critdmg',
  arm: 'arm',
  ap: 'ap',
  cld: 'cld',
  night: 'Night',
  daytime: 'Daytime',
  skillNAME_256: 'Sunset Falcon',
  DESCRIBE_256: 'Do not use special bullets',

  // new
  fairyNAME_1: 'Warrior Fairy',
  fairyNAME_2: 'Fury Fairy',
  fairyNAME_3: 'Armor Fairy',
  fairyNAME_4: 'Shield Fairy',
  fairyNAME_5: 'Defence Fairy',
  fairyNAME_6: 'Provocation Fairy',
  fairyNAME_7: 'Sniper Fairy',
  fairyNAME_8: 'Bombardment Fairy',
  fairyNAME_9: 'Airstrike Fairy',
  fairyNAME_10: 'Reinforcement  Fairy',
  fairyNAME_11: 'Airborne Fairy',
  fairyNAME_12: 'Landmine Fairy',
  fairyNAME_13: 'Rocket Fairy',
  fairyNAME_14: 'Construction Fairy',
  fairyNAME_15: 'Command Fairy',
  fairyNAME_16: 'Rescue Fairy',
  fairyNAME_17: 'Illumination Fairy',
  fairyNAME_18: 'Golden',
  fairyNAME_19: 'Kitchen Fairy',
  fairyNAME_20: 'Firework Fairy',
  fairyNAME_21: 'Nian Fairy'
}
